### ISSUE TITLE
ROS 2 Branch

### ISSUE THREAD

**Issue by DLu** [ros4hri/hri_msgs#4]
I know that ROS 2 is in the works. If the intent is to make the ROS 2 interfaces living in the same repo, can you make a ROS 2 branch for this repo?

**Comment by victorpaleologue** [comment]
I need this too because I would like to add ROS4HRI bindings to a robot running ROS 2 iron.

**Comment by severin-lemaignan** [comment]
Sorry, I should have answered to to issue waaaaay earlier! ROS 2 is now officially supported (and maintained), in the `humble-devel` branch.

**Comment by severin-lemaignan** [comment]
@victorpaleologue: out of curiosity, do you plan by any change to make Nao/Pepper ROS4HRI compatible? that would be great!

**Comment by victorpaleologue** [comment]
That was the initial plan but the contract was scaled down. I'll negotiate another one for ROS4HRI, there are good chances they are still interested. Is there any chance that the `humble-devel` branch is compatible with iron?

**Comment by severin-lemaignan** [comment]
haven't tried, but I don't see why not? (in any case, I'll be happy to merge any changes required for Iron)
